ALTER TABLE runs ADD COLUMN provider_profile TEXT NOT NULL DEFAULT 'free';
ALTER TABLE runs ADD COLUMN max_provider_calls INTEGER NOT NULL DEFAULT 500;
ALTER TABLE runs ADD COLUMN max_billable_units REAL NOT NULL DEFAULT 0;
