ALTER TABLE runs ADD COLUMN cloud_approved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN max_model_calls INTEGER NOT NULL DEFAULT 50;
ALTER TABLE runs ADD COLUMN max_model_input_tokens INTEGER NOT NULL DEFAULT 200000;
ALTER TABLE runs ADD COLUMN max_model_output_tokens INTEGER NOT NULL DEFAULT 25600;
ALTER TABLE runs ADD COLUMN max_cloud_tokens INTEGER NOT NULL DEFAULT 0;
